apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: test-tke-cluster
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.96.0.0/12"]
        pods:
            cidrBlocks: ["192.168.0.0/16"]
        serviceDomain: "cluster.local"
    providerConfig:
      value:
        apiVersion: "tkeproviderconfig/v1alpha1"
        kind: "TKEClusterProviderConfig"
        clusterName: "test-tke-cluster"
        clusterCIDR: "10.4.0.0/14"
        clusterVersion: "1.10.5"
        vpcId: "vpc-idwohtyg"
        region: "ap-beijing"
