apiVersion: v1
kind: Namespace
metadata:
  name: clusterapi
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Secret
metadata:
  name: tencent-cloud-api-secret
  namespace: clusterapi
type: Opaque
data:
  SecretId:  '!!! Get your SecretId from https://console.cloud.tencent.com/cam/capi'
  SecretKey: '!!! Get your SecretKey from https://console.cloud.tencent.com/cam/capi'
